#ifndef __CONFIG_H__
#define __CONFIG_H__

#define MPROXY_ARM_PORT								60000
#define QC_DOG_HTTP_REDIRECT_SERVER_PORT			60001
#define QC_DOG_HTTPS_REDIRECT_SERVER_PORT			60002
#define QC_DOG_AUTH_SERVER_PORT						60003
#define QC_DOG_WEB_SERVER_PORT						60004


#endif

